### ISSUE TITLE
Causing Memory Leak

### ISSUE THREAD

**Issue by ZubairAkber** [visenze/visearch-sdk-android#47]
I am using it in a fragment and i have also integrated LeakCanary, It is casing a memory leak. I am attaching an image of the LeakCanary 

![screenshot_20180625-163827](https://user-images.githubusercontent.com/15378288/41848412-d0f05586-7896-11e8-9d61-7d73934209af.png)

**Comment by hussainahmad** [comment]
any luck so far ?? facing the same issue

**Comment by yulu** [comment]
noted, we will try to fix the issue and perform the memory leak check. Thanks for reporting

**Comment by yulu** [comment]
@ZubairAkber @hussainahmad please check the latest version (1.2.3). We have tried to refactor the code to avoid the use of the anonymous class. Hope this memory leak issue can be fixed

**Comment by hussainahmad** [comment]
@yulu `latest version` is not correctly configured. kindly check the mentioned issue.  
```
Exception in thread "main" java.lang.AssertionError: Failed to load class when desugaring method com/visenze/visearch/android/http/HttpInstance$1.onErrorResponse(Lcom/android/volley/VolleyError;)V when checking the assignable relation for class java.lang.Throwable and com.android.volley.VolleyError
	at com.google.devtools.build.android.desugar.TryWithResourcesRewriter$TryWithResourceVisitor.isAssignableFrom(TryWithResourcesRewriter.java:365)
	at com.google.devtools.build.android.desugar.TryWithResourcesRewriter$TryWithResourceVisitor.isMethodCallTargeted(TryWithResourcesRewriter.java:356)
	at com.google.devtools.build.android.desugar.TryWithResourcesRewriter$TryWithResourceVisitor.visitMethodInsn(TryWithResourcesRewriter.java:336)
	at org.objectweb.asm.MethodVisitor.visitMethodInsn(MethodVisitor.java:485)
	at com.google.devtools.build.android.desugar.ObjectsRequireNonNullMethodRewriter$ObjectsMethodInlinerMethodVisitor.visitMethodInsn(ObjectsRequireNonNullMethodRewriter.java:55)
	at org.objectweb.asm.MethodVisitor.visitMethodInsn(MethodVisitor.java:485)
	at com.google.devtools.build.android.desugar.LongCompareMethodRewriter$LongCompareMethodVisitor.visitMethodInsn(LongCompareMethodRewriter.java:52)
	at org.objectweb.asm.MethodVisitor.visitMethodInsn(MethodVisitor.java:485)
	at com.google.devtools.build.android.desugar.Java7Compatibility$UpdateBytecodeVersionIfNecessary.visitMethodInsn(Java7Compatibility.java:148)
	at org.objectweb.asm.MethodVisitor.visitMethodInsn(MethodVisitor.java:485)
	at com.google.devtools.build.android.desugar.InterfaceDesugaring$InterfaceInvocationRewriter.visitMethodInsn(InterfaceDesugaring.java:423)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1600)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
	at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:477)
	at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:361)
	at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:314)
	at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:711)
Caused by: java.lang.ClassNotFoundException: Class com.android.volley.VolleyError not found
	at com.google.devtools.build.android.desugar.HeaderClassLoader.findClass(HeaderClassLoader.java:53)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.google.devtools.build.android.desugar.TryWithResourcesRewriter$TryWithResourceVisitor.isAssignableFrom(TryWithResourcesRewriter.java:362)
	... 18 more
```

**Comment by yulu** [comment]
@ZubairAkber @hussainahmad could you please try out the latest released SDK, hope the issues has been fixed. (version 1.3.0)
